### ISSUE TITLE
如何直接跳转至应用的权限管理

### ISSUE THREAD

**Issue by mlick** [SpikeKing/wcl-permission-demo#1]
请问大神，如何直接跳转至应用的权限管理呢？

**Comment by SpikeKing** [comment]
跳转不了啊, 原生Rom可以提示跳转到应用设置, 定制的没法弄, 只能指导用户了, Android-23好坑, 动态权限只能这么解决了.

**Comment by mlick** [comment]
好吧，谢谢了！
