### ISSUE TITLE
这个方案是不是够严谨？

### ISSUE THREAD

**Issue by baoyachi** [SpikeKing/wcl-permission-demo#2]
的确,这样是可以解决入口时权限验证，但是当用户进入app后，在使用期间关闭权限，当使用时，还是要进行权限验证，以确保程序不会崩溃……个人建议，仅供参考

**Comment by mlick** [comment]
@baoyachi  可以在每当要使用某个功能时都进行验证。

**Comment by fykcwkf** [comment]
自己运行了下，在每次读敏感权限时，都会弹出是否设置权限的问题,,,解决了不没有权限时，崩溃的时候

**Comment by SpikeKing** [comment]
具体的解决方案是这样的, 在每个Activity的基类中都需要检查, 避免用户在运行时的关闭情况, 这是最优方案!
